server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/cwi-challenge
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true